### ISSUE TITLE
Add support for ARM Linux

### ISSUE THREAD

**Issue by F-Pape** [Sauci/a2l-grpc#6]
I would like to use this library on a RaspberryPi like board, but I'm unable to, because currently only the amd64 files are generated for Linux. Ideally we would have an arm and an arm64 .so file.

**Comment by Sauci** [comment]
Hello @F-Pape , thanks for your contribution. I just ran your workflow, and it seems to build. Could you give it a try on your target and confirm it is working? You will find the artefacts [here](https://github.com/Sauci/a2l-grpc/actions/runs/8632856123).

**Comment by F-Pape** [comment]
I tried to use the generated artefacts and they work on my platform
